import type { Metadata } from "next";
import Link from "next/link";
import {
	ContentSection,
	FAQList,
	NumberedGrid,
	PageHero,
	ProductCTA,
} from "@/components/marketing/PagePrimitives";
import { appLinks, product } from "@/data/product";
import { pageMetadata } from "@/lib/metadata";

export const metadata: Metadata = pageMetadata({
	title: "Kontinue AI Model | Native AI Inside Kontinue AI",
	description:
		"Learn about K-AI 1.0, how Kontinue AI’s native intelligence works alongside leading AI models, and how users can preserve context while switching models.",
	path: "/kontinue-model",
});

const faqs = [
	{
		question: "Does Kontinue AI have its own model?",
		answer:
			"K-AI 1.0 is our proprietary intelligence and orchestration layer, not a foundation model trained from scratch. Its primary language runtime is Gemma 4 31B Instruct, with gpt-oss-120b available as a reliability fallback.",
	},
	{
		question: "Can K-AI 1.0 generate images?",
		answer:
			"The K-AI 1.0 language runtime produces text. When image generation is available in your plan, the Kontinue experience sends that work to our separate K-Image service; it is not generated by the K-AI language model itself.",
	},
	{
		question: "Can I still use other AI models?",
		answer:
			"Yes. We also provide selected models from leading external providers. Model availability and limits depend on your plan.",
	},
	{
		question: "Can I switch models during a conversation?",
		answer:
			"Yes. You can choose another supported model for the next response while keeping the conversation history in the same thread.",
	},
	{
		question: "Can I import a previous conversation?",
		answer:
			"Yes. We support selected shared-link and export-file import methods. See the import guide for the current list.",
	},
	{
		question: "Is K-AI 1.0 available on the free plan?",
		answer:
			"Yes. K-AI 1.0 is available on Free, Starter, Plus, Pro, and Max. Monthly request, context, output, and AI usage-credit allowances vary by plan.",
	},
];

export default function KontinueModelPage() {
	return (
		<>
			<PageHero
				eyebrow="The Kontinue AI model"
				title="Meet K-AI 1.0"
				description="The native intelligence layer inside Kontinue AI, designed to provide a complete AI experience while preserving the freedom to use other supported models."
				primary={{
					label: "Try K-AI 1.0",
					href: appLinks.signUp,
					eventName: "kontinue_model_cta_clicked",
				}}
				secondary={{
					label: "View supported models",
					href: "/supported-models",
				}}
				breadcrumbs={[
					{ name: "Home", href: "/" },
					{ name: "K-AI 1.0", href: "/kontinue-model" },
				]}
			/>

			<ContentSection
				eyebrow="What it is"
				title="Kontinue intelligence, presented transparently"
				description={product.nativeModel.transparency}
			>
				<NumberedGrid
					items={[
						{
							title: "Native by default",
							description:
								"K-AI 1.0 appears first as the Kontinue-native option in the model picker.",
						},
						{
							title: "Product-aware",
							description:
								"It works with Kontinue capabilities such as memory, retrieval, projects, tasks, connectors, and specialised agents.",
						},
						{
							title: "Choice remains",
							description:
								"Start with K-AI, import an existing conversation, or choose another supported model when the work calls for it.",
						},
					]}
				/>
			</ContentSection>

			<ContentSection
				tone="muted"
				eyebrow="Supported work"
				title="What you can do with K-AI 1.0"
			>
				<div className="mt-12 flex flex-wrap gap-3">
					{product.nativeModel.supportedTasks.map((task) => (
						<span
							key={task}
							className="rounded-full border border-border bg-card px-5 py-3 text-sm font-medium"
						>
							{task}
						</span>
					))}
				</div>
			</ContentSection>

			<ContentSection
				eyebrow="Why it exists"
				title="A native Kontinue experience, with model freedom"
				description="We believe Kontinue AI should offer more than a list of external APIs. K-AI brings our own product intelligence into the platform while we keep supported third-party models available for different tasks."
			>
				<div className="mt-10 flex flex-wrap gap-5 text-sm">
					<Link
						href="/import-ai-conversations"
						className="link-underline font-medium text-brand-strong"
					>
						Import and continue a conversation
					</Link>
					<Link
						href="/supported-models"
						className="link-underline font-medium text-brand-strong"
					>
						Compare supported model providers
					</Link>
				</div>
			</ContentSection>

			<ContentSection
				tone="dark"
				eyebrow="Runtime transparency"
				title="K-AI 1.0 at a glance"
				description="K-AI combines our product intelligence with an openly identified primary language model. These details describe the runtime currently configured in Kontinue AI."
			>
				<div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
					{[
						["Current version", product.nativeModel.version],
						["Release date", product.nativeModel.releaseDate],
						[
							"Primary language model",
							product.nativeModel.primaryLanguageModel,
						],
						["Supported languages", product.nativeModel.supportedLanguages],
					].map(([label, value]) => (
						<div
							key={label}
							className="rounded-2xl border border-background/10 bg-background/[0.05] p-5"
						>
							<p className="font-mono text-[0.65rem] uppercase tracking-widest text-background/45">
								{label}
							</p>
							<p className="mt-3 text-sm leading-relaxed text-background/80">
								{value}
							</p>
						</div>
					))}
				</div>
				<div className="mt-8 rounded-2xl border border-background/10 bg-background/[0.03] p-6 sm:p-8">
					<div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
						<div>
							<p className="font-mono text-[0.65rem] uppercase tracking-widest text-background/45">
								Published base-model results
							</p>
							<h3 className="font-display mt-3 text-2xl">
								Gemma 4 31B Instruct benchmarks
							</h3>
						</div>
						<a
							href={product.nativeModel.primaryModelCard}
							target="_blank"
							rel="noopener noreferrer"
							className="link-underline text-sm font-medium text-background/75 hover:text-background"
						>
							Read Google DeepMind&apos;s model card
						</a>
					</div>
					<div className="mt-7 grid gap-px overflow-hidden rounded-xl border border-background/10 bg-background/10 sm:grid-cols-2 lg:grid-cols-4">
						{product.nativeModel.publishedBenchmarks.map((benchmark) => (
							<div key={benchmark.name} className="bg-foreground p-5">
								<p className="font-display text-3xl text-background">
									{benchmark.score}
								</p>
								<p className="mt-2 text-xs leading-relaxed text-background/55">
									{benchmark.name}
								</p>
							</div>
						))}
					</div>
					<p className="mt-5 text-sm leading-relaxed text-background/60">
						These are Google DeepMind&apos;s published results for the primary
						base model—not a claim that the complete K-AI product receives the
						same score. If the primary route is unavailable, K-AI can fall back
						to {product.nativeModel.fallbackLanguageModel}.
					</p>
				</div>
				<div className="mt-8 rounded-2xl border border-background/10 p-6">
					<h3 className="font-display text-xl">Known limitations</h3>
					<ul className="mt-4 space-y-2 text-sm text-background/65">
						{product.nativeModel.knownLimitations.map((item) => (
							<li key={item}>• {item}</li>
						))}
					</ul>
				</div>
			</ContentSection>

			<FAQList items={faqs} centered />
			<ProductCTA
				title="Start with K-AI 1.0. Switch when the work needs something else."
				description="One AI platform for native Kontinue intelligence, supported external models, and portable conversations."
				eventName="kontinue_model_signup_clicked"
			/>
		</>
	);
}
