/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Source: packages/tailwind-config/shared-styles.css
 * Regenerate: bun run theme:sync (from apps/mobile-app)
 *
 * Every Kontinue color is authored on the web side. Editing this file by hand
 * reintroduces the drift it exists to prevent.
 */

export const THEMES = [
	"normal",
	"pink",
	"emerald",
	"chelsea",
	"amethyst",
] as const;

export type Theme = (typeof THEMES)[number];

/** The dark-first default, mirroring web's fallback theme. */
export const DEFAULT_THEME: Theme = "normal";

export const THEME_LABELS: Record<Theme, string> = {
	normal: "Default",
	pink: "Pink",
	emerald: "Emerald",
	chelsea: "Chelsea Blue",
	amethyst: "Amethyst",
};

export const TOKEN_NAMES = [
	"accent",
	"accent-foreground",
	"background",
	"border",
	"card",
	"card-foreground",
	"chart-1",
	"chart-2",
	"chart-3",
	"chart-4",
	"chart-5",
	"destructive",
	"foreground",
	"input",
	"muted",
	"muted-foreground",
	"popover",
	"popover-foreground",
	"primary",
	"primary-foreground",
	"ring",
	"secondary",
	"secondary-foreground",
	"sidebar",
	"sidebar-accent",
	"sidebar-accent-foreground",
	"sidebar-border",
	"sidebar-foreground",
	"sidebar-primary",
	"sidebar-primary-foreground",
	"sidebar-ring",
] as const;

export type TokenName = (typeof TOKEN_NAMES)[number];

export type ColorScheme = "light" | "dark";

/**
 * Every token for every theme, in both schemes, converted from the web
 * `oklch()` values to hex because React Native cannot parse oklch at runtime.
 */
export const THEME_TOKENS: Record<
	Theme,
	Record<ColorScheme, Record<TokenName, string>>
> = {
	normal: {
		light: {
			"accent": "#eeeeee",
			"accent-foreground": "#030303",
			"background": "#ffffff",
			"border": "#e4e4e4",
			"card": "#fcfcfc",
			"card-foreground": "#030303",
			"chart-1": "#030303",
			"chart-2": "#222222",
			"chart-3": "#484848",
			"chart-4": "#717171",
			"chart-5": "#9e9e9e",
			"destructive": "#bb061e",
			"foreground": "#030303",
			"input": "#e4e4e4",
			"muted": "#f5f5f5",
			"muted-foreground": "#484848",
			"popover": "#ffffff",
			"popover-foreground": "#030303",
			"primary": "#000000",
			"primary-foreground": "#ffffff",
			"ring": "#030303",
			"secondary": "#f5f5f5",
			"secondary-foreground": "#161616",
			"sidebar": "#fafafa",
			"sidebar-accent": "#f2f2f2",
			"sidebar-accent-foreground": "#030303",
			"sidebar-border": "#e4e4e4",
			"sidebar-foreground": "#161616",
			"sidebar-primary": "#030303",
			"sidebar-primary-foreground": "#fafafa",
			"sidebar-ring": "#030303",
		},
		dark: {
			"accent": "#121212",
			"accent-foreground": "#ffffff",
			"background": "#000000",
			"border": "#161616",
			"card": "#060606",
			"card-foreground": "#f8f8f8",
			"chart-1": "#f8f8f8",
			"chart-2": "#bebebe",
			"chart-3": "#868686",
			"chart-4": "#525252",
			"chart-5": "#292929",
			"destructive": "#861118",
			"foreground": "#f8f8f8",
			"input": "#161616",
			"muted": "#0b0b0b",
			"muted-foreground": "#808080",
			"popover": "#020202",
			"popover-foreground": "#f8f8f8",
			"primary": "#ffffff",
			"primary-foreground": "#000000",
			"ring": "#dedede",
			"secondary": "#0b0b0b",
			"secondary-foreground": "#f8f8f8",
			"sidebar": "#000000",
			"sidebar-accent": "#060606",
			"sidebar-accent-foreground": "#ffffff",
			"sidebar-border": "#121212",
			"sidebar-foreground": "#f8f8f8",
			"sidebar-primary": "#ffffff",
			"sidebar-primary-foreground": "#000000",
			"sidebar-ring": "#dedede",
		},
	},
	pink: {
		light: {
			"accent": "#eb8e99",
			"accent-foreground": "#260d10",
			"background": "#ffffff",
			"border": "#d9bfcf",
			"card": "#ffffff",
			"card-foreground": "#0b090a",
			"chart-1": "#ed0c97",
			"chart-2": "#e052aa",
			"chart-3": "#e084bd",
			"chart-4": "#8e0b5c",
			"chart-5": "#5e073d",
			"destructive": "#e5010c",
			"foreground": "#0b090a",
			"input": "#d9bfcf",
			"muted": "#eadce5",
			"muted-foreground": "#95507b",
			"popover": "#ffffff",
			"popover-foreground": "#0b090a",
			"primary": "#ed0c97",
			"primary-foreground": "#f3f1f2",
			"ring": "#ed0c97",
			"secondary": "#eadce5",
			"secondary-foreground": "#21121b",
			"sidebar": "#eadce5",
			"sidebar-accent": "#eb8e99",
			"sidebar-accent-foreground": "#260d10",
			"sidebar-border": "#d9bfcf",
			"sidebar-foreground": "#21121b",
			"sidebar-primary": "#ed0c97",
			"sidebar-primary-foreground": "#f3f1f2",
			"sidebar-ring": "#ed0c97",
		},
		dark: {
			"accent": "#331f2d",
			"accent-foreground": "#e8e3e7",
			"background": "#0d080a",
			"border": "#2f1824",
			"card": "#28151f",
			"card-foreground": "#f3f1f2",
			"chart-1": "#e82ca0",
			"chart-2": "#ed5eb7",
			"chart-3": "#f589cc",
			"chart-4": "#931f67",
			"chart-5": "#5f2047",
			"destructive": "#e5010c",
			"foreground": "#f3f1f2",
			"input": "#2f1824",
			"muted": "#301d29",
			"muted-foreground": "#b398a9",
			"popover": "#28151f",
			"popover-foreground": "#f3f1f2",
			"primary": "#e82ca0",
			"primary-foreground": "#f3f1f2",
			"ring": "#e82ca0",
			"secondary": "#301d29",
			"secondary-foreground": "#f6eff3",
			"sidebar": "#0d080a",
			"sidebar-accent": "#331f2d",
			"sidebar-accent-foreground": "#e8e3e7",
			"sidebar-border": "#2f1824",
			"sidebar-foreground": "#f3f1f2",
			"sidebar-primary": "#e82ca0",
			"sidebar-primary-foreground": "#f3f1f2",
			"sidebar-ring": "#e82ca0",
		},
	},
	emerald: {
		light: {
			"accent": "#a9e9c4",
			"accent-foreground": "#0d2617",
			"background": "#ffffff",
			"border": "#d0dece",
			"card": "#ffffff",
			"card-foreground": "#0a0b09",
			"chart-1": "#3ce82d",
			"chart-2": "#5ee052",
			"chart-3": "#8ce085",
			"chart-4": "#178e0c",
			"chart-5": "#0f5e07",
			"destructive": "#e5010c",
			"foreground": "#0a0b09",
			"input": "#d0dece",
			"muted": "#edf3ec",
			"muted-foreground": "#569550",
			"popover": "#ffffff",
			"popover-foreground": "#0a0b09",
			"primary": "#3ce82d",
			"primary-foreground": "#f1f3f1",
			"ring": "#3ce82d",
			"secondary": "#edf3ec",
			"secondary-foreground": "#132112",
			"sidebar": "#edf3ec",
			"sidebar-accent": "#a9e9c4",
			"sidebar-accent-foreground": "#0d2617",
			"sidebar-border": "#d0dece",
			"sidebar-foreground": "#132112",
			"sidebar-primary": "#3ce82d",
			"sidebar-primary-foreground": "#f1f3f1",
			"sidebar-ring": "#3ce82d",
		},
		dark: {
			"accent": "#52e08d",
			"accent-foreground": "#ecf9f1",
			"background": "#0f1b0e",
			"border": "#3b5d38",
			"card": "#172815",
			"card-foreground": "#f1f3f1",
			"chart-1": "#59e04d",
			"chart-2": "#6aed5e",
			"chart-3": "#92f589",
			"chart-4": "#28931f",
			"chart-5": "#256020",
			"destructive": "#e5010c",
			"foreground": "#f1f3f1",
			"input": "#3b5d38",
			"muted": "#283a27",
			"muted-foreground": "#9ab398",
			"popover": "#172815",
			"popover-foreground": "#f1f3f1",
			"primary": "#59e04d",
			"primary-foreground": "#f1f3f1",
			"ring": "#59e04d",
			"secondary": "#283a27",
			"secondary-foreground": "#eff6ee",
			"sidebar": "#264224",
			"sidebar-accent": "#52e08d",
			"sidebar-accent-foreground": "#ecf9f1",
			"sidebar-border": "#3b5d38",
			"sidebar-foreground": "#f1f3f1",
			"sidebar-primary": "#59e04d",
			"sidebar-primary-foreground": "#f1f3f1",
			"sidebar-ring": "#59e04d",
		},
	},
	chelsea: {
		light: {
			"accent": "#f8bf32",
			"accent-foreground": "#3a2805",
			"background": "#f8fafe",
			"border": "#d3dbea",
			"card": "#ffffff",
			"card-foreground": "#122046",
			"chart-1": "#1938ba",
			"chart-2": "#5280e8",
			"chart-3": "#f8bf32",
			"chart-4": "#3566b8",
			"chart-5": "#1a306d",
			"destructive": "#e5010c",
			"foreground": "#122046",
			"input": "#d3dbea",
			"muted": "#ebf0fb",
			"muted-foreground": "#536383",
			"popover": "#ffffff",
			"popover-foreground": "#122046",
			"primary": "#1938ba",
			"primary-foreground": "#ffffff",
			"ring": "#1938ba",
			"secondary": "#e2ecff",
			"secondary-foreground": "#182a5a",
			"sidebar": "#dfe8fa",
			"sidebar-accent": "#d0ddf6",
			"sidebar-accent-foreground": "#182a5a",
			"sidebar-border": "#cdd6e9",
			"sidebar-foreground": "#182a5a",
			"sidebar-primary": "#1938ba",
			"sidebar-primary-foreground": "#ffffff",
			"sidebar-ring": "#1938ba",
		},
		dark: {
			"accent": "#f0b92f",
			"accent-foreground": "#10182b",
			"background": "#0b111f",
			"border": "#283452",
			"card": "#131b2e",
			"card-foreground": "#f2f5fc",
			"chart-1": "#456fe9",
			"chart-2": "#6e9bfb",
			"chart-3": "#f0b92f",
			"chart-4": "#2f60b2",
			"chart-5": "#2e447d",
			"destructive": "#e5010c",
			"foreground": "#f2f5fc",
			"input": "#283452",
			"muted": "#1d273e",
			"muted-foreground": "#9da8be",
			"popover": "#131b2e",
			"popover-foreground": "#f2f5fc",
			"primary": "#456fe9",
			"primary-foreground": "#ffffff",
			"ring": "#456fe9",
			"secondary": "#1b2746",
			"secondary-foreground": "#eef2f9",
			"sidebar": "#11192c",
			"sidebar-accent": "#f0b92f",
			"sidebar-accent-foreground": "#10182b",
			"sidebar-border": "#27324d",
			"sidebar-foreground": "#eef2f9",
			"sidebar-primary": "#456fe9",
			"sidebar-primary-foreground": "#ffffff",
			"sidebar-ring": "#f0b92f",
		},
	},
	amethyst: {
		light: {
			"accent": "#eaa9d8",
			"accent-foreground": "#260d20",
			"background": "#ffffff",
			"border": "#dbcedf",
			"card": "#ffffff",
			"card-foreground": "#0b090b",
			"chart-1": "#bc2ce8",
			"chart-2": "#bf52e1",
			"chart-3": "#cb84e0",
			"chart-4": "#6f0b8e",
			"chart-5": "#4a075e",
			"destructive": "#e5010c",
			"foreground": "#0b090b",
			"input": "#dbcedf",
			"muted": "#f1ecf3",
			"muted-foreground": "#855095",
			"popover": "#ffffff",
			"popover-foreground": "#0b090b",
			"primary": "#bc2ce8",
			"primary-foreground": "#f3f1f3",
			"ring": "#bc2ce8",
			"secondary": "#f1ecf3",
			"secondary-foreground": "#1e1221",
			"sidebar": "#f1ecf3",
			"sidebar-accent": "#eaa9d8",
			"sidebar-accent-foreground": "#260d20",
			"sidebar-border": "#dbcedf",
			"sidebar-foreground": "#1e1221",
			"sidebar-primary": "#bc2ce8",
			"sidebar-primary-foreground": "#f3f1f3",
			"sidebar-ring": "#bc2ce8",
		},
		dark: {
			"accent": "#e052ba",
			"accent-foreground": "#f8ecf5",
			"background": "#180e1b",
			"border": "#54385c",
			"card": "#241528",
			"card-foreground": "#f3f1f3",
			"chart-1": "#bd4ddf",
			"chart-2": "#cc5eed",
			"chart-3": "#dc89f6",
			"chart-4": "#781f93",
			"chart-5": "#512060",
			"destructive": "#e5010c",
			"foreground": "#f3f1f3",
			"input": "#54385c",
			"muted": "#36273a",
			"muted-foreground": "#ad98b3",
			"popover": "#241528",
			"popover-foreground": "#f3f1f3",
			"primary": "#bd4ddf",
			"primary-foreground": "#f3f1f3",
			"ring": "#bd4ddf",
			"secondary": "#36273a",
			"secondary-foreground": "#f4eef6",
			"sidebar": "#3b2342",
			"sidebar-accent": "#e052ba",
			"sidebar-accent-foreground": "#f8ecf5",
			"sidebar-border": "#54385c",
			"sidebar-foreground": "#f3f1f3",
			"sidebar-primary": "#bd4ddf",
			"sidebar-primary-foreground": "#f3f1f3",
			"sidebar-ring": "#bd4ddf",
		},
	},
};
