import { useState } from "react";
import {
  Palette,
  Sparkles,
  Code2,
  Eye,
  Copy,
  Check,
} from "lucide-react";
import { useSidebar } from "@/components/ui/sidebar";
import FloatingSidebarButtonGroup from "@/components/layout/sidebar/FloatingSidebarButtonGroup";

export default function CanvasView() {
  const { state } = useSidebar();
  const isCollapsed = state === "collapsed";
  const [prompt, setPrompt] = useState("");
  const [activeTab, setActiveTab] = useState<"preview" | "code">("preview");
  const [copied, setCopied] = useState(false);

  // Demo interactive canvas artifact generated by Kontinue AI Canvas
  const demoHtml = `<div style="font-family: system-ui, sans-serif; padding: 2.5rem; background: #09090b; color: #fff; border-radius: 1.5rem; border: 1px solid rgba(255,255,255,0.1); max-width: 500px; margin: auto; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5);">
  <div style="display: flex; align-items: center; gap: 0.75rem; margin-bottom: 1.5rem;">
    <div style="width: 2.5rem; height: 2.5rem; border-radius: 0.75rem; background: linear-gradient(135deg, #a855f7, #6366f1); display: flex; align-items: center; justify-content: center; font-weight: bold;">K</div>
    <div>
      <h2 style="font-size: 1.25rem; font-weight: 700; margin: 0;">Kontinue Canvas</h2>
      <p style="font-size: 0.75rem; color: rgba(255,255,255,0.5); margin: 0;">Interactive UI Component</p>
    </div>
  </div>
  <p style="font-size: 0.875rem; color: rgba(255,255,255,0.8); line-height: 1.6;">
    Welcome to Kontinue AI Canvas sandbox! Describe any UI component, poster, layout, or document to generate interactive artifacts live.
  </p>
  <button style="margin-top: 1.5rem; width: 100%; padding: 0.75rem; border-radius: 0.75rem; background: #fff; color: #000; font-weight: 600; border: none; cursor: pointer;">
    Explore Canvas Artifacts
  </button>
</div>`;

  const handleCopyCode = () => {
    navigator.clipboard.writeText(demoHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative flex h-full w-full bg-background text-foreground overflow-hidden">
      {isCollapsed && <FloatingSidebarButtonGroup />}
      {/* Left Design Prompt & Controls Panel */}
      <div className="flex w-96 flex-col border-r border-white/[0.08] bg-[#161619] p-5 space-y-5">
        <div className="flex items-center gap-2 text-white font-semibold text-sm">
          <Palette size={18} />
          <span>Canvas Design Studio</span>
        </div>

        <p className="text-xs leading-relaxed text-foreground/50">
          Design interactive web components, artifacts, landing pages, posters, and full layouts with live preview.
        </p>

        <div className="flex-1 flex flex-col justify-between space-y-4">
          <div className="space-y-3">
            <label className="text-xs font-semibold text-foreground/70">Design Prompt</label>
            <div className="relative rounded-2xl border border-white/[0.1] bg-black/40 p-3 shadow-inner">
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Describe a component, poster, or page design..."
                rows={5}
                className="w-full resize-none bg-transparent text-xs text-foreground outline-none placeholder:text-foreground/35"
              />
              <button
                type="button"
                className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-2 text-xs font-semibold text-black shadow-lg transition-all hover:bg-white/90"
              >
                <Sparkles size={14} />
                <span>Generate Canvas</span>
              </button>
            </div>
          </div>

          {/* Quick Presets */}
          <div className="space-y-2">
            <p className="text-[11px] font-semibold text-foreground/45 uppercase tracking-wider">Preset Templates</p>
            <div className="flex flex-col gap-1.5">
              {["SaaS Landing Hero", "Dashboard Card Widget", "Interactive Pricing Table", "Gradient Hero Banner"].map((preset) => (
                <button
                  key={preset}
                  type="button"
                  onClick={() => setPrompt(`Design a sleek ${preset}`)}
                  className="rounded-xl border border-white/[0.06] bg-white/[0.025] px-3 py-2 text-left text-xs text-foreground/70 transition-all hover:border-white/30 hover:bg-white/[0.06] hover:text-foreground"
                >
                  {preset}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Right Canvas Interactive Sandbox & Code Preview */}
      <div className="flex flex-1 flex-col overflow-hidden bg-[#0d0d0f]">
        {/* Canvas Toolbar */}
        <div className="flex h-12 items-center justify-between border-b border-white/[0.06] px-6 bg-black/20">
          <div className="flex items-center gap-1 rounded-xl bg-white/[0.04] p-1 border border-white/[0.06]">
            <button
              type="button"
              onClick={() => setActiveTab("preview")}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1 text-xs font-medium transition-all ${
                activeTab === "preview"
                  ? "bg-white/[0.12] text-foreground font-semibold"
                  : "text-foreground/50 hover:text-foreground"
              }`}
            >
              <Eye size={13} />
              <span>Preview</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("code")}
              className={`flex items-center gap-1.5 rounded-lg px-3 py-1 text-xs font-medium transition-all ${
                activeTab === "code"
                  ? "bg-white/[0.12] text-foreground font-semibold"
                  : "text-foreground/50 hover:text-foreground"
              }`}
            >
              <Code2 size={13} />
              <span>Code HTML/CSS</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleCopyCode}
              className="flex items-center gap-1.5 rounded-xl border border-white/[0.08] bg-white/[0.04] px-3 py-1.5 text-xs text-foreground/70 hover:bg-white/[0.08] hover:text-foreground"
            >
              {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
              <span>{copied ? "Copied Code" : "Copy Code"}</span>
            </button>
          </div>
        </div>

        {/* Canvas Render Area */}
        <div className="flex-1 overflow-auto p-8 flex items-center justify-center">
          {activeTab === "preview" ? (
            <div
              className="w-full max-w-2xl"
              dangerouslySetInnerHTML={{ __html: demoHtml }}
            />
          ) : (
            <pre className="w-full max-w-3xl overflow-x-auto rounded-2xl border border-white/[0.1] bg-black/80 p-6 font-mono text-xs leading-relaxed text-foreground/90">
              <code>{demoHtml}</code>
            </pre>
          )}
        </div>
      </div>
    </div>
  );
}
