/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  post?: PostReference;
  authorName?: string;
  text?: string;
  createdAt?: string;
  status?: "pending" | "approved" | "rejected";
  approved?: boolean;
  submitterHash?: string;
  contentHash?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?:
    | "Product"
    | "Engineering"
    | "AI Models"
    | "Tutorials"
    | "Research"
    | "Company";
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  featured?: boolean;
  views?: number;
  body?: BlockContent;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: string;
  x?: string;
  linkedin?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | PostReference
  | Comment
  | BlockContent
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(_createdAt desc) {			_id,	title,	"slug": slug.current,	excerpt,	"publishedAt": coalesce(publishedAt, _createdAt),	"modifiedAt": _updatedAt,	featured,	"views": coalesce(views, 0),	"readMins": round(length(pt::text(body)) / 1200),	mainImage{ ..., "lqip": asset->metadata.lqip },	seo,	"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },	"categories": categories[]->{ title, "slug": slug.current }	}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string;
  modifiedAt: string;
  featured: boolean | null;
  views: number | 0;
  readMins: number;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    lqip: string | null;
  } | null;
  seo: Seo | null;
  author: {
    name: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    x: string | null;
    linkedin: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    title:
      | "AI Models"
      | "Company"
      | "Engineering"
      | "Product"
      | "Research"
      | "Tutorials"
      | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{		_id,		title,		"slug": slug.current,		excerpt,		"publishedAt": coalesce(publishedAt, _createdAt),		"modifiedAt": _updatedAt,		mainImage{ ..., "lqip": asset->metadata.lqip },		"seo": {			"title": coalesce(seo.title, title),			"description": coalesce(seo.description, excerpt),			"image": coalesce(seo.image, mainImage),			"noIndex": seo.noIndex == true		},		body,		"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },		"categories": categories[]->{ title, "slug": slug.current }	}
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string;
  modifiedAt: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    lqip: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    noIndex: boolean | false;
  };
  body: BlockContent | null;
  author: {
    name: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    x: string | null;
    linkedin: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    title:
      | "AI Models"
      | "Company"
      | "Engineering"
      | "Product"
      | "Research"
      | "Tutorials"
      | null;
    slug: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && slug.current != $slug && count((categories[]._ref)[@ in *[_type == "post" && slug.current == $slug][0].categories[]._ref]) > 0]		| order(_createdAt desc)[0...3] {			_id,	title,	"slug": slug.current,	excerpt,	"publishedAt": coalesce(publishedAt, _createdAt),	"modifiedAt": _updatedAt,	featured,	"views": coalesce(views, 0),	"readMins": round(length(pt::text(body)) / 1200),	mainImage{ ..., "lqip": asset->metadata.lqip },	seo,	"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },	"categories": categories[]->{ title, "slug": slug.current }	}
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string;
  modifiedAt: string;
  featured: boolean | null;
  views: number | 0;
  readMins: number;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    lqip: string | null;
  } | null;
  seo: Seo | null;
  author: {
    name: string | null;
    role: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    x: string | null;
    linkedin: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    title:
      | "AI Models"
      | "Company"
      | "Engineering"
      | "Product"
      | "Research"
      | "Tutorials"
      | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHORS_QUERY
// Query: *[_type == "author" && defined(slug.current)] | order(name asc) {		_id, name, role, bio, x, linkedin, image, "slug": slug.current	}
export type AUTHORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  x: string | null;
  linkedin: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_QUERY
// Query: *[_type == "author" && slug.current == $slug][0] {		_id, name, role, bio, x, linkedin, image, "slug": slug.current,		"posts": *[_type == "post" && author._ref == ^._id && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {				_id,	title,	"slug": slug.current,	excerpt,	"publishedAt": coalesce(publishedAt, _createdAt),	"modifiedAt": _updatedAt,	featured,	"views": coalesce(views, 0),	"readMins": round(length(pt::text(body)) / 1200),	mainImage{ ..., "lqip": asset->metadata.lqip },	seo,	"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },	"categories": categories[]->{ title, "slug": slug.current }		}	}
export type AUTHOR_QUERY_RESULT = {
  _id: string;
  name: string | null;
  role: string | null;
  bio: string | null;
  x: string | null;
  linkedin: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: string | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    publishedAt: string;
    modifiedAt: string;
    featured: boolean | null;
    views: number | 0;
    readMins: number;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      lqip: string | null;
    } | null;
    seo: Seo | null;
    author: {
      name: string | null;
      role: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      bio: string | null;
      x: string | null;
      linkedin: string | null;
      slug: string | null;
    } | null;
    categories: Array<{
      title:
        | "AI Models"
        | "Company"
        | "Engineering"
        | "Product"
        | "Research"
        | "Tutorials"
        | null;
      slug: string | null;
    }> | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SITEMAP_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && seo.noIndex != true] {		"slug": slug.current,		_updatedAt	}
export type SITEMAP_POSTS_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_COMMENTS_QUERY
// Query: *[		_type == "comment" &&		post._ref == *[_type == "post" && slug.current == $slug][0]._id &&		(status == "approved" || (!defined(status) && approved == true))	] | order(createdAt desc)[0...100] {		_id,		"authorName": coalesce(authorName, "Guest"),		text,		createdAt	}
export type POST_COMMENTS_QUERY_RESULT = Array<{
  _id: string;
  authorName: string | "Guest";
  text: string | null;
  createdAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: COMMENT_SUBMISSION_CONTEXT_QUERY
// Query: {		"post": *[			_type == "post" &&			_id == $postId &&			!(_id in path("drafts.**"))		][0] { _id, "slug": slug.current },		"recentCount": count(*[			_type == "comment" &&			submitterHash == $submitterHash &&			createdAt > $rateCutoff		]),		"isDuplicate": count(*[			_type == "comment" &&			submitterHash == $submitterHash &&			contentHash == $contentHash &&			createdAt > $duplicateCutoff		]) > 0	}
export type COMMENT_SUBMISSION_CONTEXT_QUERY_RESULT = {
  post: {
    _id: string;
    slug: string | null;
  } | null;
  recentCount: number;
  isDuplicate: boolean;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t*[_type == "post" && defined(slug.current)] | order(_createdAt desc) {\n\t\t\n\t_id,\n\ttitle,\n\t"slug": slug.current,\n\texcerpt,\n\t"publishedAt": coalesce(publishedAt, _createdAt),\n\t"modifiedAt": _updatedAt,\n\tfeatured,\n\t"views": coalesce(views, 0),\n\t"readMins": round(length(pt::text(body)) / 1200),\n\tmainImage{ ..., "lqip": asset->metadata.lqip },\n\tseo,\n\t"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },\n\t"categories": categories[]->{ title, "slug": slug.current }\n\n\t}\n': POSTS_QUERY_RESULT;
    '\n\t*[_type == "post" && slug.current == $slug][0]{\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\texcerpt,\n\t\t"publishedAt": coalesce(publishedAt, _createdAt),\n\t\t"modifiedAt": _updatedAt,\n\t\tmainImage{ ..., "lqip": asset->metadata.lqip },\n\t\t"seo": {\n\t\t\t"title": coalesce(seo.title, title),\n\t\t\t"description": coalesce(seo.description, excerpt),\n\t\t\t"image": coalesce(seo.image, mainImage),\n\t\t\t"noIndex": seo.noIndex == true\n\t\t},\n\t\tbody,\n\t\t"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },\n\t\t"categories": categories[]->{ title, "slug": slug.current }\n\t}\n': POST_QUERY_RESULT;
    '\n\t*[_type == "post" && defined(slug.current) && slug.current != $slug && count((categories[]._ref)[@ in *[_type == "post" && slug.current == $slug][0].categories[]._ref]) > 0]\n\t\t| order(_createdAt desc)[0...3] {\n\t\t\n\t_id,\n\ttitle,\n\t"slug": slug.current,\n\texcerpt,\n\t"publishedAt": coalesce(publishedAt, _createdAt),\n\t"modifiedAt": _updatedAt,\n\tfeatured,\n\t"views": coalesce(views, 0),\n\t"readMins": round(length(pt::text(body)) / 1200),\n\tmainImage{ ..., "lqip": asset->metadata.lqip },\n\tseo,\n\t"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },\n\t"categories": categories[]->{ title, "slug": slug.current }\n\n\t}\n': RELATED_POSTS_QUERY_RESULT;
    '\n\t*[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n\t*[_type == "author" && defined(slug.current)] | order(name asc) {\n\t\t_id, name, role, bio, x, linkedin, image, "slug": slug.current\n\t}\n': AUTHORS_QUERY_RESULT;
    '\n\t*[_type == "author" && slug.current == $slug][0] {\n\t\t_id, name, role, bio, x, linkedin, image, "slug": slug.current,\n\t\t"posts": *[_type == "post" && author._ref == ^._id && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n\t\t\t\n\t_id,\n\ttitle,\n\t"slug": slug.current,\n\texcerpt,\n\t"publishedAt": coalesce(publishedAt, _createdAt),\n\t"modifiedAt": _updatedAt,\n\tfeatured,\n\t"views": coalesce(views, 0),\n\t"readMins": round(length(pt::text(body)) / 1200),\n\tmainImage{ ..., "lqip": asset->metadata.lqip },\n\tseo,\n\t"author": author->{ name, role, image, bio, x, linkedin, "slug": slug.current },\n\t"categories": categories[]->{ title, "slug": slug.current }\n\n\t\t}\n\t}\n': AUTHOR_QUERY_RESULT;
    '\n\t*[_type == "post" && defined(slug.current) && seo.noIndex != true] {\n\t\t"slug": slug.current,\n\t\t_updatedAt\n\t}\n': SITEMAP_POSTS_QUERY_RESULT;
    '\n\t*[\n\t\t_type == "comment" &&\n\t\tpost._ref == *[_type == "post" && slug.current == $slug][0]._id &&\n\t\t(status == "approved" || (!defined(status) && approved == true))\n\t] | order(createdAt desc)[0...100] {\n\t\t_id,\n\t\t"authorName": coalesce(authorName, "Guest"),\n\t\ttext,\n\t\tcreatedAt\n\t}\n': POST_COMMENTS_QUERY_RESULT;
    '\n\t{\n\t\t"post": *[\n\t\t\t_type == "post" &&\n\t\t\t_id == $postId &&\n\t\t\t!(_id in path("drafts.**"))\n\t\t][0] { _id, "slug": slug.current },\n\t\t"recentCount": count(*[\n\t\t\t_type == "comment" &&\n\t\t\tsubmitterHash == $submitterHash &&\n\t\t\tcreatedAt > $rateCutoff\n\t\t]),\n\t\t"isDuplicate": count(*[\n\t\t\t_type == "comment" &&\n\t\t\tsubmitterHash == $submitterHash &&\n\t\t\tcontentHash == $contentHash &&\n\t\t\tcreatedAt > $duplicateCutoff\n\t\t]) > 0\n\t}\n': COMMENT_SUBMISSION_CONTEXT_QUERY_RESULT;
  }
}
