// Kode IDE docs RAG. Fetches official docs through Rust (no renderer CORS),
// keeps ONE shared local index in the app data dir (not Convex, not per-project,
// to save storage), and retrieves relevant chunks to ground answers.
//
// Only the single configured URL per source is fetched (not a full crawl), so
// the index stays small.

import { invoke } from "@tauri-apps/api/core";
import {
  indexAllSources,
  loadDocSources,
  sourcesDueForRefresh,
  type DocChunk,
} from "@repo/ai/lib/docs/indexer";
import { buildDocsContext, retrieveDocs } from "@repo/ai/lib/docs/retriever";
// Prebuilt index bundled with the app (generated by `bun run build:docs`) so
// docs grounding works on first launch with zero cold start. Empty until built.
import seedChunks from "./kode-docs-seed.json";

let chunksCache: DocChunk[] | null = null;
let indexing = false;

const rustFetch = (url: string) => invoke<string>("kode_fetch_text", { url });

async function loadIndex(): Promise<DocChunk[]> {
  if (chunksCache) return chunksCache;
  try {
    const raw = await invoke<string>("kode_docs_load");
    if (raw) {
      chunksCache = JSON.parse(raw) as DocChunk[];
      return chunksCache;
    }
  } catch {
    // fall through to the bundled seed
  }
  // No fresh on-disk index → use the prebuilt seed for instant grounding. The
  // startup refresh will fetch live docs and persist them over this.
  chunksCache = (seedChunks as DocChunk[]) ?? [];
  return chunksCache;
}

/** Build (or rebuild) the local docs index in the background. Safe to call often. */
export async function buildDocsIndex(): Promise<void> {
  if (indexing) return;
  indexing = true;
  try {
    const chunks = await indexAllSources(loadDocSources(), rustFetch);
    chunksCache = chunks;
    await invoke("kode_docs_save", { contents: JSON.stringify(chunks) });
  } catch (error) {
    console.warn(`[docs] indexing failed: ${String(error)}`);
  } finally {
    indexing = false;
  }
}

/**
 * Warm the docs index at app startup so the first chat message is already
 * grounded. Builds it if missing, refreshes only the stale sources, and never
 * blocks — runs in the background. The index persists on disk across sessions,
 * so after the first launch this is usually a no-op or a quiet refresh.
 */
export async function ensureDocsIndexed(): Promise<void> {
  const chunks = await loadIndex();
  if (chunks.length === 0) {
    void buildDocsIndex();
    return;
  }
  const lastByFramework: Record<string, string> = {};
  for (const chunk of chunks) {
    const seen = lastByFramework[chunk.framework];
    if (!seen || chunk.lastIndexed > seen) {
      lastByFramework[chunk.framework] = chunk.lastIndexed;
    }
  }
  if (sourcesDueForRefresh(loadDocSources(), lastByFramework).length > 0) {
    void buildDocsIndex();
  }
}

export type DocSourceRef = { title: string; url: string };

/**
 * Retrieve a citable docs block + the unique sources for the query. If the index
 * is empty, kicks off a background build and returns nothing this turn — never
 * blocks the chat on a network fetch.
 */
export async function retrieveDocsContext(
  query: string,
  framework?: string | null,
): Promise<{ context: string; sources: DocSourceRef[] }> {
  const chunks = await loadIndex();
  if (chunks.length === 0) {
    void buildDocsIndex();
    return { context: "", sources: [] };
  }
  const top = retrieveDocs(query, chunks, { framework, topK: 4 });
  const seen = new Set<string>();
  const sources: DocSourceRef[] = [];
  for (const chunk of top) {
    if (seen.has(chunk.sourceUrl)) continue;
    seen.add(chunk.sourceUrl);
    sources.push({ title: `${chunk.framework} — ${chunk.title}`, url: chunk.sourceUrl });
  }
  return { context: buildDocsContext(top), sources };
}
